# NumPy Examples

In [6]:
# Importing the NumPy library
import numpy as np

In [7]:
# Creating a 1D NumPy array
arr_1d = np.array([1, 2, 3, 4, 5])
arr_2d = np.array([[1,2,3],[4,5,6]])
arr_3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [62]:
print(arr_1d)
print(arr_1d.ndim) # shows its dimension

[1 2 3 4 5]
1


In [9]:
print(arr_2d)
print(arr_2d.ndim) # shows its dimension

[[1 2 3]
 [4 5 6]]
2


In [10]:
print(arr_3d)
print(arr_3d.ndim) # shows its dimension

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3


In [21]:
#Arange (from, to, step size)
arange = np.arange(0,11,2)
print(arange)

[ 0  2  4  6  8 10]


## Shape

In [27]:
print(arr_1d.shape)
print(arr_2d.shape)
print(arr_3d.shape)

(5,)
(2, 3)
(2, 2, 3)


## Zeros , Ones, Full

In [37]:
#Full with 0.0
zeros_1d = np.zeros(10)
print(zeros_1d)

#Full with 0
zeros_1d = np.zeros(10,int) # or (10,dtype=int)
print(zeros_1d)

zeros_2d = np.zeros((10,3))
print(zeros_2d)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0 0 0 0 0 0 0 0 0 0]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [38]:
#Full with 1.0
ones_1d = np.ones(10)
print(ones_1d)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [39]:
#Full with default value
full_1d = np.full(10,2)
print(full_1d)

[2 2 2 2 2 2 2 2 2 2]


In [41]:
# Rgular Intervel (from, to, no of elements)
np.linspace(0,10,50,dtype=float)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [48]:
print(np.eye(5))
print(np.eye(5,4))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]


### Convert data type

In [34]:
print(zeros_1d.astype(int))
print(ones_1d.astype(int))

[0 0 0 0 0 0 0 0 0 0]
[1 1 1 1 1 1 1 1 1 1]


## Array Operations

In [53]:
# Element-wise addition
addition_result = arr_1d + arr_1d
print(addition_result)

scalar_addition_result = arr_2d + 200
print(scalar_addition_result)

[ 2  4  6  8 10]
[[201 202 203]
 [204 205 206]]


In [56]:
# Element-wise multiplication
multiplication_result = arr_1d * 2
print(multiplication_result)

mul_arr = arr_1d * arr_1d
print(mul_arr)

[ 2  4  6  8 10]
[ 1  4  9 16 25]


In [57]:
print(arr_2d/2) # / Fload division

[[0.5 1.  1.5]
 [2.  2.5 3. ]]


In [58]:
print(arr_2d//2) # // Int division

[[0 1 1]
 [2 2 3]]


In [87]:
#Transpose array
print(arr_2d.T) 
print(np.transpose(arr_2d))

[[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]


In [81]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [84]:
arr_2d_new = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr_2d_new1 = np.array([[1,2],[4,5]])
print(np.matmul(arr_2d_new,arr_2d_new))

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


In [85]:
print(np.matmul(arr_2d_new1,arr_2d_new1))

[[ 9 12]
 [24 33]]


In [83]:
print(np.matmul(arr_2d,arr_2d))

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

In [47]:
# Matrix multiplication (dot product)
dot_product_result = np.dot(arr_2d, np.transpose(arr_2d))
print(dot_product_result)

[[14 32]
 [32 77]]


In [48]:
# Element-wise square root
sqrt_result = np.sqrt(arr_1d)
print(sqrt_result)

[1.         1.41421356 1.73205081 2.         2.23606798]


In [49]:
# Element-wise exponentiation
exp_result = np.exp(arr_1d)
print(exp_result)

[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [50]:
# Sum of all elements
sum_result = np.sum(arr_1d)
print(sum_result)

15


In [51]:
# Mean of all elements
mean_result = np.mean(arr_2d)
print(mean_result)

3.5


## Indexing and Slicing

In [16]:
# Accessing an element
element = arr_2d[1, 2] #[row no, col no]
print(element)

6


In [14]:
# Slicing rows and columns
row_slice = arr_2d[0, :]
col_slice = arr_2d[:, 1]
print(row_slice)
print(col_slice)

[1 2 3]
[2 5]


In [17]:
# Slicing with conditions
condition_slice = arr_1d[arr_1d > 2]
print(condition_slice)

[3 4 5]


In [24]:
#3d array Slicing rows and columns
slice_3d = arr_3d[0,0,0] #[3d to 2d, 2d to 1d, 1d to 0d]
slice_3d

1

## Reshaping and Manipulating Arrays

In [90]:
# Reshaping an array
print(arr_1d.reshape(1, 5))

[[1 2 3 4 5]]


In [91]:
# Flattening an array
print(arr_2d.flatten())

[1 2 3 4 5 6]


In [92]:
# Transposing an array
print(np.transpose(arr_2d))

[[1 4]
 [2 5]
 [3 6]]


In [93]:
# Stacking arrays vertically
print(np.vstack((arr_1d, arr_1d)))

[[1 2 3 4 5]
 [1 2 3 4 5]]


In [94]:
# Stacking arrays horizontally
print(np.hstack((arr_1d, arr_1d)))

[1 2 3 4 5 1 2 3 4 5]


## Statistical Functions

In [52]:
# Minimum value
print(np.min(arr_1d))
print(np.argmin(arr_1d))

1
0


In [53]:
# Maximum value
print(np.max(arr_2d))
print(np.argmax(arr_2d))

6
5


In [55]:
# Standard deviation
print(np.std(arr_1d))

1.4142135623730951


In [57]:
# Median
print(np.median(arr_1d))

3.0


In [107]:
# Correlation coefficient
arr_1d_new = np.array([10,15,12])
print(np.corrcoef(arr_1d_new, arr_2d[0]))

[[1.         0.39735971]
 [0.39735971 1.        ]]


## Random Number Generation

In [50]:
# Generating random integers
print(np.random.randint(1, 10, size=(3, 3)))
print(np.random.rand(2))
print(np.random.rand(4,4))

[[8 5 6]
 [9 7 2]
 [7 5 9]]
[0.16339998 0.12219246]
[[0.87979837 0.81415225 0.60719242 0.88739462]
 [0.44427573 0.06716469 0.6151906  0.30318201]
 [0.64234077 0.23419591 0.36340913 0.44622724]
 [0.63226731 0.70975178 0.09693601 0.15201026]]


#### Or

In [59]:
from numpy .random import randint
print(randint(1,10,size=(3,3)))

[[8 6 2]
 [1 6 9]
 [6 9 7]]


In [109]:
# Generating random numbers from a normal distribution
print(np.random.normal(0, 1, size=(2, 2)))

[[-0.40160392  0.73047446]
 [ 0.53471417  0.57941899]]


In [110]:
# Generating random numbers from a uniform distribution
print(np.random.uniform(0, 1, size=(3, 3)))

[[0.88188607 0.56815233 0.53344456]
 [0.7203448  0.07579835 0.50411978]
 [0.26492943 0.37077209 0.22450732]]


## nan,inf

In [68]:
array1 = np.array([0,1,2,3,4])
array2 = np.array([1,2,3,4,5])

In [71]:
print(array1 / array1)
#Waring about nan value. but it executes as normal

[nan  1.  1.  1.  1.]


C:\Users\Rajes\AppData\Local\Temp\ipykernel_1600\310892321.py:1: RuntimeWarning: invalid value encountered in divide
  print(array1 / array1)


In [72]:
print(array2 / array1)

[       inf 2.         1.5        1.33333333 1.25      ]


C:\Users\Rajes\AppData\Local\Temp\ipykernel_1600\4143201180.py:1: RuntimeWarning: divide by zero encountered in divide
  print(array2 / array1)


## Broadcasting

In [114]:
# Broadcasting operations
print(arr_2d + arr_1d_new)

[[11 17 15]
 [14 20 18]]


## Saving and Loading Arrays

In [58]:
print(arr_3d.dtype)

int32


In [116]:
# Saving an array to a file
np.save('my_array.npy', arr_2d)

In [117]:
# Loading an array from a file
loaded_array = np.load('my_array.npy')

# END